### ISSUE TITLE
Column not found issue  in 1.4.5

### ISSUE THREAD

**Issue by shion-w** [slingdata-io/sling-cli#546]
## Issue Description

- Description of the issue: 

Currently moving data from MSSQL cdc tables -> Snowflake. 
After upgrading to 1.4.5 there seem to be a breaking change that doesn't allow the reference of one of the metadata columns in the cdc tables. 
Don't know what exactly is causing this, and if its a column naming thing or a sling configuration that I need to specify, but just wanted to bring it up. 

Current solution was to roll back to 1.4.4 and everything is working as is. 

- Sling version (`sling --version`): 

1.4.5

- Operating System (`linux`, `mac`, `windows`): 

windows

- Replication Configuration: 

```yaml
  dbo.TBL_NAME:
    object: SCHEMA_NAME.TBL_NAME
    sql: |
      SELECT
        sys.fn_cdc_map_lsn_to_time(__$start_lsn) AS _cdc_timestamp
        , __$start_lsn
      FROM [cdc].[fn_cdc_get_all_changes_dbo_TBL_NAME}]
          (sys.fn_cdc_get_min_lsn('dbo_TBL_NAME')
          , sys.fn_cdc_get_max_lsn(), N'all')
```

- Log Output (please run command with `-d`): 

```
~ Error executing query
000904 (42000): SQL compilation error: error line 1 at position 111
invalid identifier '__$START_LSN' -- mssql cdc metadata column

```

**Comment by flarco** [comment]
Interesting, what might be happening is the column casing, see https://github.com/slingdata-io/sling-cli/issues/538#issuecomment-2799022785

You could try with `source_options.column_casing = source` if that is the case.

If that doesn work, do you mind running with v1.4.5, with the `--trace` flag, and copy/paste the query that's being submitted?

**Comment by shion-w** [comment]
Looks like that did the trick, thank you for help!
